dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path ('', views.index, name = 'index'),
]

item/urls.py
from django.urls import path

from . import views

app_name = 'item' #name of app folder

urlpatterns = [
    path('', views.items, name='items'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),  
    path('<int:pk>/delete/', views.delete, name='delete'),  
    path('<int:pk>/edit/', views.edit, name='edit'),  
]

onlinestore/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('', include('storeapp.urls')),
    path('items/', include('item.urls')), #This is the path for the urls.py file created in the "item" app folder
    path('admin/', admin.site.urls),
    path('inbox/', include('conversation.urls')),
    path('dashboard/', include('dashboard.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  #this is not advised in production purposes

storeapp/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .forms import LoginForm

app_name = "storeapp"

urlpatterns = [  
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view( template_name = 'storeapp/login.html', authentication_form = LoginForm), name='login'),

]

storeapp/models.py
from django.db import models

# Create your models here.

storeapp/forms.py
from django import forms # type: ignore
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm # type: ignore
from django.contrib.auth.models import User # type: ignore

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget = forms.TextInput(attrs= {
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl' 
    }))
    password = forms.CharField(widget = forms.PasswordInput(attrs= {
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl' 
    }))

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    username = forms.CharField(widget = forms.TextInput(attrs= {
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl' 
    }))
    email = forms.CharField(widget = forms.EmailInput(attrs= {
        'placeholder': 'Your email',
        'class': 'w-full py-4 px-6 rounded-xl' 
    }))
    password1 = forms.CharField(widget = forms.PasswordInput(attrs= {
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl' 
    }))
    password2 = forms.CharField(widget = forms.PasswordInput(attrs= {
        'placeholder': 'Repeat password',
        'class': 'w-full py-4 px-6 rounded-xl' 
    }))

storeapp/views.py
from django.shortcuts import render,redirect
from item.models import Category, Item   #"item.models" --> where "item" is the name of the app folder the models.py file exists

from .forms import SignupForm

def index(request):
    items = Item.objects.filter(is_sold = False)[0:6]
    categories = Category.objects.all()

    return render(request, "storeapp/index.html", {
        'categories': categories,
        'items': items, 
    })

def contact(request):
    return render(request, 'storeapp/contact.html')

def signup(request):
    if request.method == 'post':
        form = SignupForm(request.post)

        if form.is_valid():
            form.save()

            return redirect('/login/')
    else:
        form = SignupForm()

    return render(request, 'storeapp/signup.html', {
        'form': form 
    })

storeapp/templates/storeapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title> {% block title %} {% endblock %} | Store</title>
</head>
<body>
    <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
        <a href="/" class="text-xl font-semibold">Puddle</a>

        <div class="space-x-6">
            <a href="{% url 'item:new' %}" class="text-lg font-semibold hover:text-gray-500">New item</a>
            <a href="{% url 'item:items' %}" class="text-lg font-semibold hover:text-gray-500">Browse</a>

            {% if request.user.is_authenticated %}
                <a href="#" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Inbox</a>
                <a href="{% url 'dashboard:index' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Dashboard</a>
            {% else %}
                <a href="{% url 'storeapp:signup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign Up</a>
                <a href="{% url 'storeapp:login' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Log in</a>
            {% endif %}
        </div>
    </nav>
    <div class="px-6 py-6 ">
        {% block content %}
        {% endblock %}
    </div>

    <footer class="py-6 px-6 flex justify-between bg-gray-800">
        <div class="w-2/3 pr-10">
            <h3 class="mb-5 font-semibold text-gray-400">About</h3>
            <p class="text-lg text-gray-500">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quasi nam incidunt accusantium?</p>
        </div>

        <div class="w-1/3">
            <div class="mb-5 font-semibold text-gray-400">Menu</div>

            <ul class="space-y-2">
                <li> <a href="#" class="text-lg text-teal-500 hover:text-teal-700">About</a> </li>
                <li> <a href= "{% url 'storeapp:contact' %}" class="text-lg text-teal-500 hover:text-teal-700">Contact</a> </li>
                <li> <a href="#" class="text-lg text-teal-500 hover:text-teal-700">Privacy policy</a> </li>
                <li> <a href="#" class="text-lg text-teal-500 hover:text-teal-700">Terms of use</a> </li>
            </ul>
        </div>
    </footer>
</body>
</html>

storeapp/templates/storeapp/contact.html
{% extends 'storeapp/base.html' %}

{% block title %} Contact {% endblock %}

{% block content %}
    <h1>The contact page</h1>
{% endblock %}

storeapp/templates/storeapp/index.html
{% extends 'storeapp/base.html' %}

{% block title %} Welcome {% endblock %}

{% block content %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Newest items</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for item in items %}
                <div>
                    <a href=" {% url 'item:detail' item.id %} ">  <!--The link you see here is that to the details page, where item.id represents the primary key(pk)-->
                        <div><img src={{item.image.url}} alt="#" class="rounded-t-xl" ></div>

                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{item.name}}</h2>
                            <p class="text-gray-500">Price: {{item.price}} </p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Categories</h2>

        <div class="grid grid-cols-3 gap-3">
            {%for category in categories%}
            <div>
                <a href="">
                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{category.name}}</h2>
                        <p class="text-gray-500"> {{category.items.count}} item(s)</p>
                    </div>
                </a>
            </div>
            {%endfor%}
        </div>

    </div>
{% endblock %}

storeapp/templates/storeapp/login.html
{% extends 'storeapp/base.html' %}


{% block title %} Log In {% endblock %}

{% block content %}
    <div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl">Log In</h1>

        <form action="." method="post">  <!--The dot represents that it takes the action from the same page we are on-->
            {% csrf_token %}

             

            <div class="mb-3">
                <label for="" class="inline-block mb-2" >Username</label><br>
                {{form.username}}  <!--dsiplays the input box for typing the username-->
            </div>

            <div class="mb-3">
                <label for="" class="inline-block mb-2" >Password</label><br>
                {{form.password}}  <!--dsiplays the input box for typing the password-->
            </div>

            

            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 bg-red-100 rounded-xl">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}

                    {{ form.non_field_errors }}  <!--for checking errors in the form-->
                </div>
            {% endif %}

            <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white" >Submit</button>
        </form>
    </div>
{% endblock %}

storeapp/templates/storeapp/signup.html
{% extends 'storeapp/base.html' %}


{% block title %} Sign Up {% endblock %}

{% block content %}
    <div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl">Sign up</h1>

        <form action="." method="post">  <!--The dot represents that it takes the action from the same page we are on-->
            {% csrf_token %}

             

            <div class="mb-3">
                <label for="" class="inline-block mb-2" >Username</label><br>
                {{form.username}}  <!--dsiplays the input box for typing the username-->
            </div>

            <div class="mb-3">
                <label for="" class="inline-block mb-2" >Email</label><br>
                {{form.email}}  <!--dsiplays the input box for typing the email-->
            </div>

            <div class="mb-3">
                <label for="" class="inline-block mb-2" >Password</label><br>
                {{form.password1}}  <!--dsiplays the input box for typing the password-->
            </div>

            <div class="mb-3">
                <label for="" class="inline-block mb-2" >Repeat password</label><br>
                {{form.password2}}  <!--dsiplays the input box for typing the password-->
            </div>

            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 bg-red-100 rounded-xl">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}

                    {{ form.non_field_errors }}  <!--for checking errors in the form-->
                </div>
            {% endif %}

            <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white" >Submit</button>
        </form>
    </div>
{% endblock %}