item/urls.py
from django.urls import path

from . import views

app_name = 'item' #name of app folder

urlpatterns = [
    path('', views.items, name='items'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),  
    path('<int:pk>/delete/', views.delete, name='delete'),  
    path('<int:pk>/edit/', views.edit, name='edit'),  
]

onlinestore/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('', include('storeapp.urls')),
    path('items/', include('item.urls')), #This is the path for the urls.py file created in the "item" app folder
    path('admin/', admin.site.urls),
    path('inbox/', include('conversation.urls')),
    path('dashboard/', include('dashboard.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  #this is not advised in production purposes

item/models.py
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ('name',)   #This is to order the categories in aplhabetical order
        verbose_name_plural = 'Categories'  #This code is written to correct the wrong plural spelling in the admin panel

    def __str__(self):  #The underscores are double on both sides of the word "str"
        return self.name  #This line of code is to return the actual names of the created categories in the admin instead of the default names given by the system
    

class Item(models.Model):
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)  #"on_delete=models.CASCADE" ensures that if a category is deleted all of its items are deleted as well
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)  #blank and null are = "True" incase a user does not want to provide one
    price = models.FloatField() 
    image = models.ImageField(upload_to='item_images', blank=True, null=True) #item_images is a folder that the images are uploaded to
    is_sold = models.BooleanField(default=False)
    created_by =models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)  #"on_delete=models.CASCADE" ensures that if a user is deleted all of his items are deleted as well
    created_at = models.DateTimeField(auto_now_add=True) #date for when item was added/created

    def __str__(self):
        return self.name

item/forms.py
from django import forms

from .models import Item

INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border' #setting INPUT_CLASSES as a variable

class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('category', 'name', 'description', 'price', 'image',)

        widgets = {
            'category': forms.Select(attrs = {           #seleccting the category section and styling it. The "forms.Select" creates a select field similar to using the select tag in html
                'class': INPUT_CLASSES
            }),
            'name': forms.TextInput(attrs = {           #seleccting the name section and styling it
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs = {           
                'class': INPUT_CLASSES
            }),
            'price': forms.TextInput(attrs = {           
                'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs = {           
                'class': INPUT_CLASSES
            }),
        }

class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('name', 'description', 'price', 'image', 'is_sold', )

        widgets = {
            'name': forms.TextInput(attrs = {           #seleccting the name section and styling it
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs = {           
                'class': INPUT_CLASSES
            }),
            'price': forms.TextInput(attrs = {           
                'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs = {           
                'class': INPUT_CLASSES
            }),
        }

item/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required #This is imported so users can only have access if they are logged in
from django.db.models import Q #helps search in multiple fields

from .forms import NewItemForm, EditItemForm
from .models import Category, Item

def items(request):
    query = request.GET.get('query', '') #the second parameter is left empty so that if there's no found query, it will return empty
    category_id = request.GET.get('category', 0)
    categories = Category.objects.all()
    items = Item.objects.filter(is_sold = False)
    

    if category_id:  #Checks if category_id has a value (i.e., it is not None, 0, or an empty string)
        items = items.filter(category_id = category_id)

    if query:
        items = items.filter(Q(name__icontains = query) | Q(description__icontains = query)) #"name__icontains" has a double underscore( __ ) signifying a field lookup
    
    return render(request, 'item/items.html', {
        'items': items,
        'query': query,
        'categories': categories,
        'category_id': int(category_id), 
    } )

def detail(request, pk):  #pk stands for primary key
    item = get_object_or_404(Item, pk=pk) #first pk is the one we get from the model itself and the other is the one we get from the url
                                          #get_object_or_404 means, get that page or  display a 404 error

    related_items = Item.objects.filter(category = item.category, is_sold = False).exclude(pk=pk)[0:3] #This line of code filters out the items in the same categories that are not sold, and displays them,
                                                                                                  #excluding only the item image that has been clicked on by means of using the primary key to differentiate it
    

    return render(request, 'item/detail.html', {
        'item': item,
        "related_items":related_items
    })        

@login_required
def new(request):
    if request.method == 'POST':
        form = NewItemForm(request.POST, request.FILES)

        if form.is_valid():
            item = form.save(commit=False)  #It is not saved directly and "False" because the field has not been created in the database if it does save directly, hence generating an error 
            item.created_by =request.user
            item.save()

            return redirect('item:detail', pk=item.id)
        
    else:
        form = NewItemForm()

    return render(request, 'item/form.html', {
           'form': form,
           'title': 'New item',
    })

@login_required
def edit(request, pk):
    item = get_object_or_404(Item, pk = pk, created_by = request.user)

    if request.method == 'POST':
        form = EditItemForm(request.POST, request.FILES, instance=item)

        if form.is_valid():
            form.save()

            return redirect('item:detail', pk=item.id)
        
    else:
        form = EditItemForm(instance = item)

    return render(request, 'item/form.html', {
           'form': form,
           'title': 'Edit item',
    })


# This request is to delete an item
@login_required
def delete(request, pk):
    item = get_object_or_404(Item, pk = pk, created_by = request.user)
    item .delete()

    return redirect('dashboard:index')

item/templates/item/detail.html
{% extends 'storeapp/base.html' %}

{% block title %} {{ item.name }} {% endblock %}

{% block content %}
    <div class="grid grid-cols-5 gap-6">
        <div class="col-span-3">
            <img src=" {{item.image.url}} " alt=""  class="rounded-xl">
        </div>

        <div class="col-span-2 p-6 bg-gray-100 rounded-xl">
            <h1 class="mb-6 text-3xl"> {{item.name}} </h1>
            <p class="text-gray-500" ><strong>Price: {{item.price}} </strong></p>
            <p class="text-gray-500" ><strong>Seller: {{item.created_by.username}} </strong></p>

            {% if item.description %}
                <p class="text-gray-700" >
                    <strong class="text-gray-500">Description</strong><br> {{item.description}}
                </p>
            {%endif%}

            {% if request.user == item.created_by %}
                <div class="mt-6 p-6 bg-white rounded-xl">
                    <p>This is your item</p>

                    <a href="{% url 'item:edit' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl">Edit</a>
                    <a href="{% url 'item:delete' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl">Delete</a>
                </div>
            {% else %}
                <a href="#" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white hover:bg-teal-700 rounded-xl">Contact seller</a>
            {% endif %}

        </div>
    </div>

    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Related items</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for item in related_items %}
                <div>
                    <a href=" {% url 'item:detail' item.id %} ">  <!--The link you see here is that to the details page, where item.id represents the primary key(pk)-->
                        <div><img src={{item.image.url}} alt="#" class="rounded-t-xl" ></div>

                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{item.name}}</h2>
                            <p class="text-gray-500">Price: {{item.price}} </p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

item/templates/item/form.html
{% extends 'storeapp/base.html' %}

{% block title %} {{title}} {% endblock %}  <!--the "title"  in the brackets is from the views.py file within the function for this form-->


{% block content %}

    <h1 class="mb-6 text-3xl">{{title}}</h1>

    <form action="." method="post" enctype="multipart/form-data"> <!--enctype attribute is needed in order to upload the images-->
        {% csrf_token %}

        <div class="space-y-4">
            {{form.as_p}}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}  <!--for checking errors in the form-->
            </div>
        {% endif %}

        <button class="mt-6 py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white" >Submit</button>
    </form>

{% endblock %}

item/templates/item/items.html
{% extends 'storeapp/base.html' %}


{% block title %} Items {% endblock %}

{% block content %}
    <div class="pb-6 grid grid-cols-4 gap-4 bg-gray-100">
        <div class="col-span-1">
            <form action="{% url 'item:items' %}" method="get">
                <input name="query" type="text" value="{{query}}" placeholder="Find a bike, a chair or car.... " class="w-full py-4 px-6 border rounded-xl">

                <button class="mt-2 py-4 px-8 text-lg bg-teal-500 text-white rounded-xl">Search</button>
            </form>

            <hr class="my-6" >

            <p class="font-semibold">Categories</p>

            <ul>
                {% for category in categories %}
                    <li class="py-2 px-2 rounded-xl {% if category.id == category_id %} bg-gray-200 {% endif %} " >
                        <a href="{% url 'item:items' %}?query={{query}}&category={{category.id}}">{{category.name}}</a>
                    </li>
                {% endfor %}
            </ul>

            <hr class="my-6" >

            <p class="font-semibold">Clear filters</p>

            <ul>
                <li><a href="{% url 'item:items' %}" class="mt-2 py-4 px-8 inline-block bg-yellow-500 text-lg rounded-xl text-white" >Clear</a></li>
            </ul>

        </div>

        <div class="col-span-3">
            <div class="grid grid-cols-3 gap-3">
                {% for item in items %}
                    <div>
                        <a href=" {% url 'item:detail' item.id %} ">  <!--The link you see here is that to the details page, where item.id represents the primary key(pk)-->
                            <div><img src={{item.image.url}} alt="#" class="rounded-t-xl" ></div>
    
                            <div class="p-6 bg-white rounded-b-xl">
                                <h2 class="text-2xl">{{item.name}}</h2>
                                <p class="text-gray-500">Price: {{item.price}} </p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}